[workspace]
members = [ "ciro_canzone", "fibonacci",
    "hello_world", "ownership",
    "tutorial", "Calcolatrice-rust/src-tauri", "calcolatrice_test", "conta_carte", "school_organizer"]
resolver = "2"
